language: objective-c
osx_image: xcode9.3
env:
  global:
    - IOS_SIMULATOR="iPhone 6s"
    - IOS_VERSION="11.3"
xcode_workspace: UserCaches.xcworkspace
xcode_scheme: UserCachesTests
befoe_install: brew update
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace UserCaches.xcworkspace -scheme UserCachesTests CODE_SIGNING_REQUIRED=NO