language: objective-c
osx_image: xcode9.3
xcode_workspace: UserCaches.xcworkspace
xcode_scheme: UserCachesTests
befoe_install: 
  - env
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcpretty --version
script: 
  - set -o pipefail
  - xcodebuild clean build -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" | xcpretty
